In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"F:\Codes\NLP\spam.csv")

df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df['Spam'] = df['Category'].apply(lambda x : 1 if x == 'spam' else 0)

In [6]:
df.head()

,Category,Message,Spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [7]:
# Before Training

df.shape

(5572, 3)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.Message,
    df.Spam,
    test_size=0.2
)

# X_train = Training messages
# X_test = Testing messages
# y_train = Training labels
# y_test = Testing labels
# test_size=0.2 = 20% data size to go into test and 80% will remain in data set

In [9]:
X_train.shape

(4457,)

In [10]:
X_test.shape

(1115,)

In [11]:
type(X_train)

pandas.core.series.Series

In [12]:
X_train[:4]

4514    Money i have won wining number 946 wot do i do...
243     Okay. No no, just shining on. That was meant t...
1395                 R we still meeting 4 dinner tonight?
90      Yeah do! Don‘t stand to close tho- you‘ll catc...
Name: Message, dtype: object

In [14]:
X_train[:4][4514]

'Money i have won wining number 946 wot do i do next'

In [15]:
type(y_train)

pandas.core.series.Series

In [16]:
y_train[:4]

4514    1
243     0
1395    0
90      0
Name: Spam, dtype: int64

In [17]:
type(X_train.values)

numpy.ndarray

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

# Vectorizer
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)

X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59415 stored elements and shape (4457, 7774)>

In [19]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7774))

In [20]:
X_train_cv.shape

(4457, 7774)

In [21]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zyada', 'ú1', '〨ud'],
      shape=(7774,), dtype=object)

In [22]:
v.get_feature_names_out()[1000:1100]

array(['anytime', 'anyway', 'anyways', 'anywhere', 'apart', 'apartment',
       'apes', 'apeshit', 'aphex', 'apnt', 'apo', 'apologetic',
       'apologise', 'apologize', 'apology', 'app', 'apparently', 'appear',
       'appendix', 'applausestore', 'applebees', 'apples', 'application',
       'apply', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaches', 'approaching', 'appropriate',
       'approve', 'approved', 'approx', 'apps', 'appt', 'appy', 'april',
       'aproach', 'aptitude', 'ar', 'arab', 'arabian', 'arcade',
       'archive', 'ard', 'are', 'area', 'aren', 'arent', 'arestaurant',
       'aretaking', 'areyouunique', 'argentina', 'argh', 'argue',
       'arguing', 'argument', 'arguments', 'aries', 'arise', 'arises',
       'arithmetic', 'arm', 'armand', 'armenia', 'arms', 'arng', 'arngd',
       'arnt', 'around', 'aroundn', 'arr', 'arrange', 'arrested',
       'arrival', 'arrive', 'arrived', 'arsenal', 'art', 'artists',
       'arts', 'arty', 'arul', '

In [23]:
# Supported Method
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints'

In [24]:
v.vocabulary_

{'money': 4594,
 'have': 3369,
 'won': 7602,
 'wining': 7556,
 'number': 4881,
 '946': 717,
 'wot': 7637,
 'do': 2381,
 'next': 4788,
 'okay': 4938,
 'no': 4820,
 'just': 3889,
 'shining': 6108,
 'on': 4956,
 'that': 6844,
 'was': 7413,
 'meant': 4432,
 'to': 6965,
 'be': 1272,
 'signing': 6178,
 'but': 1569,
 'sounds': 6363,
 'better': 1329,
 'we': 7440,
 'still': 6504,
 'meeting': 4445,
 'dinner': 2335,
 'tonight': 6998,
 'yeah': 7705,
 'don': 2414,
 'stand': 6458,
 'close': 1849,
 'tho': 6895,
 'you': 7731,
 'll': 4173,
 'catch': 1680,
 'something': 6328,
 'appt': 1035,
 'is': 3759,
 'at': 1114,
 'lt': 4265,
 'time': 6933,
 'gt': 3273,
 'am': 925,
 'not': 4855,
 'my': 4688,
 'fault': 2802,
 'listen': 4155,
 'told': 6979,
 'twice': 7119,
 'how': 3533,
 'are': 1046,
 'doing': 2404,
 'the': 6848,
 'queen': 5548,
 'going': 3184,
 'for': 2951,
 'royal': 5867,
 'wedding': 7456,
 'hai': 3311,
 'dear': 2201,
 'friends': 3021,
 'this': 6888,
 'new': 4780,
 'amp': 943,
 'present': 5412,
 'by'

In [27]:
# To View Where the non zero values are
X_train_np = X_train_cv.toarray()
np.where(X_train_np[0] != 0)

(array([ 717, 2381, 3369, 4594, 4788, 4881, 7556, 7602, 7637]),)

In [29]:
# Training the model

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_cv, y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [30]:
X_test_cv = v.transform(X_test)

In [34]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

# 0 = Not spam & 1 = Spam
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       963
           1       0.97      0.93      0.95       152

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [33]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)

model.predict(emails_count)

array([0, 1])

In [36]:
# Different way
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [37]:
clf.fit(X_train, y_train)

,steps,"[('vectorizer', ...), ('nb', ...)]"
,transform_input,None
,memory,None
,verbose,False
,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None


In [38]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       963
           1       0.97      0.93      0.95       152

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

